# Generated by Django 4.0.2 on 2022-02-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinyl',
            name='user',
        ),
    ]
