# Generated by Django 4.0.2 on 2022-03-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_vinyl_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vinyl',
            name='user',
        ),
        migrations.AlterField(
            model_name='vinyl',
            name='description',
            field=models.TextField(max_length=500),
        ),
    ]
